matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: linux
    dist: precise
    sudo: required
  allow_failures:
  - dist: trusty
language: node_js
node_js:
- '6'
- '6.1'
script: npm test && npm run coverage
deploy:
- provider: npm
  email: sacha.st@live.fr
  api_key:
    secure: fH5Sw9Y25WiyXJ+rrnFT/03F9Rvmlhag/nVSx/kZYWwHggZljP9d1IfKGZLURSOY9FeQ0iUp6WTv/QCABQMd2XL74NbzWjLcUkREkEYSpLC0Pu8QVFt3G+oKK6Eb4MyFAFY7mp46uyGMhKuqQgdXNnc12VZPJOztxT7caXfCKpdKj9jXpkmAQsWrabxmlTu0A1clNw7R6heFOdwX1JFutXP3+ChWFIvhUu90AeO12w/kuEf/LdRFqGuaGjmBc/NFfL6dIHN81+EAuabvyOveow32B5k55WL9TYbZ1zwDdNJQyZscPPVCs4WKuABjeRMx+KP04XGVsg2Z5qfkIfbRWXbx5m5u9HZYNxzfyUjmtKgFrTZ3iKQY5DgsUkrXaahN1hlh2rCY6h9093yzk0qbSFfU8mDq0eREWeD25pR/ETC0rkQSHtg5cvHs5iPodsLPZnm6+8UgAQFfaK4SH6Ehxtvh2cjhGhsev167Vq9OXTXxcLF/VbHmHDXTkotdapFKGl48rX4SWStgrIBl38uo5B2wBz/PI3G5AqMvC8Xw6/+UziNwuY9mD/s/GLn35qgajLUSZs9vaebga/UFWFB4HLDl7ck7ml6sw3KNG9X1lQ3CDscdwwgWYGVRPi2HnwazvDyoTgEoQpzomU503YmjmH0tvvYWL19sJ8c4MF15In4=
  on:
    branch:
    - master
    - "/[0-9]+\\.[0-9]+\\.[0-9]+/"
    node: '6.1'
