matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: linux
    dist: precise
    sudo: required
  allow_failures:
  - dist: trusty

language: node_js
node_js:
- '6'
- '6.1'

env:
  GH_TOKEN:
    secure: "nUTW6x6ICfU/SB92yJI+vvgjc4PVHjM4D8u7z2AOuwtaM1PUnwGPNfl4YgSfqkdtXk2hCDb1HZJINEblxOdEe5X/ibuMID47Wslj4hXsC397hYO/8kzLwjdekmfzTt7SSlttjrxvFg/R3F6ItvU3kA5pNySFckqSOL8YVsyhMo8xklxck2IR15I9umeVyIyePct2VzigKOHyUTz8Tivd3M516bAPkf5WtpJ71cPT2rpc9DEVO5tBdpb6aErH3/4GfEA4qhA/+202c7FmM3er4ZoBHI0EjK/mmdpmTIXA1Jc5/CD1engy8FjSiqw/OEDGxEaV6HRWOYf4kWwIS5jtuZ63voM8fuIDbgxPrrFXLAzHyJJ32rSdX2MQbgLGc3sVY7x8Dcn13Xu3QL+2dlDviPRNZnZ/zvQUzXS2+XbKRVm+r/UcgYLGU5BzAdr+kl2JzaCF7nNhS/7f1BJOxxhp0rV5p1L417FkkSJXSg/8TgQ30ohdfcv8vO+VLjjQMuEWjNSTN0wQZ3ctHd40xbfURl8pXQU6Cj1XDJ9MjSEBzJyeu5wSAxmFtYFsYs6dO/exAmScnl/tQXMX6OFtcP0jQwiR5PKez7eZruBIQjfQpyK0U67KeFAIVotD8FPeGkeD2xdROj3mBQTs3VyzB89iTgvmjezVJ0Jb9penN3BDTQQ="

script:
- npm test && npm run coverage

before_deploy:
- node bin/generate-changelog.js --changelog-file CHANGELOG.md --gh-token "$GH_TOKEN" --gh-repo "$TRAVIS_REPO_SLUG"
deploy:
- provider: npm
  skip_cleanup: true
  email: sacha.st@live.fr
  api_key:
    secure: MLiTRrcPvHj8iHTPwFBPpDBIynP02cSaL1ESWZMkpL7yNAeVcyIwggivGxH0o+ir9AjALUg0IbVTJcCxswQhMywIgcFXC4SKhZKpzyyFt3pLQLBf/+sZWZNHBGlodAyMbq/ZlK9Uk6jcSPOtKMwdF47G3bBvdYDsmcyRjeJ4JUkSakuxvPAWETJhXvC1bDNt09TRfoQ/kyZa3zk1A1w2ZK4rEuVshMpHl4JI3bMsipQByK+n32s3+oJZ1W9P0Oqca+XZFPWJ0eCv9tbfwO5NgZSXQ3qTX//btNgHDHomrlgvEKFIHwTGBjAO4yqftkUKpMASQcY2NQwTcrJj5Lil1S/+7T9i760AjJ6FMwSGDWZ0CmmlNwBapJLNHXAalAaMDXc8UXxtM5DT4cH2uH1yM0WP0CAQnQhdgkOCy6b8a/QkI4/Qv19k2P4sWiEVrOrMT1zDFpctWr3R/IdX5dbd3ztChioHsSqTnv/hHThPIjlVubgYVWPs+ZueVBDWXAtoLdtY4CKHkw1sXkY2aGc0y50zpizIDUfbcsdbUiyVZZqknfYeAN5ILHpYIH4xPGW6ZWR51A7LSgQeWdxWbZTksXtlAsgBU6vOaAe01CnYmbBYl52Bu0flQx739xgKkBnDEKGh4qAWembq5rJpoFj0CTgAHnuXirCMi8hJgTkZpmw=
  on:
    branch:
    - master
    - "/[0-9]+\\.[0-9]+\\.[0-9]+/"
    node: '6'
after_deploy:
- npm run tag
