matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: linux
    dist: precise
    sudo: required
  allow_failures:
  - dist: trusty

language: node_js
node_js:
- '6'
- '6.1'

env:
  global:
    secure: lI45Snws5pDPkxQFimdyiMp57p2z8z0R/MKjwA/q2ufqta3+lj0K4jwVNZTVtzcp2BtJ+18bmqscG64G7mGprhea22a4/vFAwc7VlSmjliQYd3zW2hQm1r55lPatT7U1JEl4C3hCC7Gt5VARD0Bgj9GVDS9amCXZaQqKe05lIG3eli1rTw/xg02TEnCMe1q7r9nAUGmM83NstXZ27T4FUrRpIluSGfhRYiBotFUmFNq3VcjmbJNhIUskkJvf+MgHLsYH+So8abLKASkaIl6zH4fYou/fgQKNwXt1KER3lC7LeN5gKIrPJO2t/k+E085ie47ioM2q8fPQQZo0fUCgqMHUb7QuUKUYf5UCf/wttzyWVueXT+kh0WXuyrCLmmI4wbfFw9yM0MIy37aO9UJuzdV8bkvb9thKWqoFEDeU3lsoZoWo8ce6Q+Fo/o+toru5E/DDEmAyWeb8ioXzX717hEXXK3O/QUUO6O5E1+kKSi8foCiL2MuTfvOWhVmEvE82WwMi9A9vcE67Q4iT8d7Q8XZVG/4zlVuB6xmoPAUL5ZIThz74KD4rIgun8fru3EkkB2t0WOxk8O1bqVCDBIkRMhEhgDn1o88haNUP5PWMpDRkaw/BRALaTTnnyB1Tqz121IcJBrr8xcX9qXmQfwQiRWzrXfBhLwk6G1IFdalajbQ=
script:
- npm test && npm run coverage

before_deploy:
- node bin/generate-changelog.js --changelog-file CHANGELOG.md --gh-token "$GH_TOKEN" --gh-repo "$TRAVIS_REPO_SLUG"
- bash bin/generate-tag-release.sh --gh-token="$GH_TOKEN" --version="$npm_package_version"
deploy:
- provider: npm
  skip_cleanup: true
  email: sacha.st@live.fr
  api_key:
    secure: MLiTRrcPvHj8iHTPwFBPpDBIynP02cSaL1ESWZMkpL7yNAeVcyIwggivGxH0o+ir9AjALUg0IbVTJcCxswQhMywIgcFXC4SKhZKpzyyFt3pLQLBf/+sZWZNHBGlodAyMbq/ZlK9Uk6jcSPOtKMwdF47G3bBvdYDsmcyRjeJ4JUkSakuxvPAWETJhXvC1bDNt09TRfoQ/kyZa3zk1A1w2ZK4rEuVshMpHl4JI3bMsipQByK+n32s3+oJZ1W9P0Oqca+XZFPWJ0eCv9tbfwO5NgZSXQ3qTX//btNgHDHomrlgvEKFIHwTGBjAO4yqftkUKpMASQcY2NQwTcrJj5Lil1S/+7T9i760AjJ6FMwSGDWZ0CmmlNwBapJLNHXAalAaMDXc8UXxtM5DT4cH2uH1yM0WP0CAQnQhdgkOCy6b8a/QkI4/Qv19k2P4sWiEVrOrMT1zDFpctWr3R/IdX5dbd3ztChioHsSqTnv/hHThPIjlVubgYVWPs+ZueVBDWXAtoLdtY4CKHkw1sXkY2aGc0y50zpizIDUfbcsdbUiyVZZqknfYeAN5ILHpYIH4xPGW6ZWR51A7LSgQeWdxWbZTksXtlAsgBU6vOaAe01CnYmbBYl52Bu0flQx739xgKkBnDEKGh4qAWembq5rJpoFj0CTgAHnuXirCMi8hJgTkZpmw=
  on:
    branch:
    - master
    - "/[0-9]+\\.[0-9]+\\.[0-9]+/"
    node: '6'
after_deploy:
- npm run tag
